apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nestjs
  name: nestjs
  namespace: development
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nestjs
  strategy: {}
  template:
    metadata:
      labels:
        app: nestjs
    spec:
      containers:
      - image: workat00/usgit:1589658865
        imagePullPolicy: Always
        name: nestjs
        ports:
        - containerPort: 5005
          name: http
          protocol: TCP
