apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Use NLB
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing" # For public access
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"  # Set to "true" for internal NLB
  labels:
    app: nestjs
  name: nestjs
  namespace: development
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5005
  selector:
    app: nestjs
  type: LoadBalancer
