apiVersion: v1
kind: Service
metadata:
  labels:
    app: nestjs
  name: nestjs
  namespace: ${NAMESPACE}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5005
  selector:
    app: nestjs
  type: LoadBalancer
